"""Remove ScreenShareRequest, ClassSession, etc.

Revision ID: 5cd272dc4a34
Revises: 08e021fc7bbd
Create Date: 2025-01-11 02:53:26.440809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cd272dc4a34'
down_revision = '08e021fc7bbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting_rooms')
    op.drop_table('screen_share_requests')
    op.drop_table('class_sessions')
    op.drop_table('chat_messages')
    op.drop_table('meetings')
    op.drop_table('classsession_participants')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classsession_participants',
    sa.Column('classsession_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('joined_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['classsession_id'], ['class_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('classsession_id', 'user_id')
    )
    op.create_table('meetings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('host_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('meeting_url', sa.VARCHAR(length=512), nullable=False),
    sa.Column('meeting_slug', sa.VARCHAR(length=128), nullable=False),
    sa.Column('created_on', sa.DATETIME(), nullable=True),
    sa.Column('start_time', sa.DATETIME(), nullable=True),
    sa.Column('end_time', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_slug'),
    sa.UniqueConstraint('meeting_url')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('classsession_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('sent_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['classsession_id'], ['class_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class_sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('lecture_session_id', sa.INTEGER(), nullable=True),
    sa.Column('host_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_on', sa.DATETIME(), nullable=True),
    sa.Column('start_time', sa.DATETIME(), nullable=True),
    sa.Column('end_time', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('session_url', sa.VARCHAR(length=256), nullable=False),
    sa.Column('session_slug', sa.VARCHAR(length=128), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lecture_session_id'], ['lecture_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_slug'),
    sa.UniqueConstraint('session_url')
    )
    op.create_table('screen_share_requests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('lecturer_id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['lecturer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['lecture_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting_rooms',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.INTEGER(), nullable=False),
    sa.Column('host_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_on', sa.DATETIME(), nullable=True),
    sa.Column('start_time', sa.DATETIME(), nullable=True),
    sa.Column('end_time', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('meeting_url', sa.VARCHAR(length=256), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['lecture_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_url')
    )
    # ### end Alembic commands ###
