"""Add deadline_duration to Assignment

Revision ID: 775df64f31d6
Revises: ea3c6a3d6d16
Create Date: 2025-03-01 17:45:05.523978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '775df64f31d6'
down_revision = 'ea3c6a3d6d16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deadline_duration', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_column('deadline_duration')

    # ### end Alembic commands ###
